const publications = [
  {y:2026,t:"Inverse Reinforcement Learning of Differential Games",a:"Bosen Lian, Wenqian Xue, and Frank L. Lewis",v:"Encyclopedia of Systems and Control",i:"Encyclopedia.jpg",u:"https://doi.org/10.1016/B978-0-443-14081-5.00073-8"},
  {y:2026,t:"Inverse Reinforcement Learning for Disturbed Networked Nonlinear Systems With Data Dropouts",a:"Pengfei Shi, Wenqian Xue, Jialu Fan, Frank L. Lewis, and Bosen Lian",v:"IEEE Transactions on Neural Networks and Learning Systems",i:"draw.png",u:"https://ieeexplore.ieee.org/abstract/document/11232478"},
  {y:2026,t:"Initially Excited Asynchronous Reinforcement Learning Control With Monotonicity and Stability",a:"Jiacheng Wu, Wenqian Xue, Frank L. Lewis, and Bosen Lian",v:"IEEE Transactions on Systems, Man, and Cybernetics: Systems",i:"Initially.png",u:"https://ieeexplore.ieee.org/abstract/document/11333885"},
  {y:2025,t:"Distributed Global Nash Containment Control and Learning of Multiplayer Multiagent Systems",a:"Yizhong Zhang, Bosen Lian, Wenqian Xue, Dariusz G. Mikulski, and Gregory R. Hudas",v:"IEEE Transactions on Automation Science and Engineering",i:"Global_Nash_Containment.png",u:"https://ieeexplore.ieee.org/abstract/document/11230582"},
  {y:2025,t:"Data-Driven Optimization-Based Cost and Optimal Control Inference",a:"Jiacheng Wu, Wenqian Xue, Frank L. Lewis, and Bosen Lian",v:"IEEE Control Systems Letters",i:"wustructure2.png",u:"https://ieeexplore.ieee.org/abstract/document/11062121"},
  {y:2025,t:"Certified Data-Driven Inverse Reinforcement Learning of Markov Jump Systems",a:"Wenqian Xue, Frank L. Lewis, and Bosen Lian",v:"Automatica",i:"certifiedIRL.png",u:"https://www.sciencedirect.com/science/article/abs/pii/S0005109825001311"},
  {y:2025,t:"Inverse Value Iteration and Q-Learning: Algorithms, Stability, and Robustness",a:"Bosen Lian, Wenqian Xue, Frank L. Lewis, and Ali Davoudi",v:"IEEE Transactions on Neural Networks and Learning Systems",i:"diagram.png",u:"https://ieeexplore.ieee.org/abstract/document/10560031"},
  {y:2025,t:"Inverse Reinforcement Learning for Discrete-Time Systems With Data Dropouts",a:"Jialu Fan, Pengfei Shi, Wenqian Xue, Bosen Lian, Yunfang Cui, and Frank L. Lewis",v:"IEEE Transactions on Cybernetics",i:"Drawing1.png",u:"https://ieeexplore.ieee.org/abstract/document/10899191"},
  {y:2025,t:"Nash-Minmax Strategy for Multiplayer Multiagent Graphical Games With Reinforcement Learning",a:"Bosen Lian, Wenqian Xue, Frank L. Lewis, and Ali Davoudi",v:"IEEE Transactions on Control of Network Systems",i:"structure.png",u:"https://ieeexplore.ieee.org/abstract/document/10574349"},
  {y:2024,t:"Integral and Inverse Reinforcement Learning for Optimal Control Systems and Games",a:"Bosen Lian, Wenqian Xue, Frank L. Lewis, Hamidreza Modares, and Bahare Kiumarsi",v:"Springer",i:"book.png",u:"https://link.springer.com/book/10.1007/978-3-031-45252-9"},
  {y:2024,t:"Distributed Dynamic Clustering and Consensus in Multiagent Systems",a:"Bosen Lian, Ahmet Taha Koru, Wenqian Xue, Frank L. Lewis, and Ali Davoudi",v:"IEEE Transactions on Automatic Control",i:"diagm.png",u:"https://ieeexplore.ieee.org/abstract/document/10491342"},
  {y:2024,t:"Model-Free Inverse H∞ Control for Imitation Learning",a:"Wenqian Xue, Bosen Lian, Yusuf Kartal, Jialu Fan, Tianyou Chai, and Frank L. Lewis",v:"IEEE Transactions on Automation Science and Engineering",i:"modelfreeHIRL.png",u:"https://ieeexplore.ieee.org/abstract/document/10606296"},
  {y:2024,t:"Distributed Minmax Strategy for Multiplayer Games: Stability, Robustness, and Algorithms",a:"Bosen Lian, Vrushabh S. Donge, Wenqian Xue, Frank L. Lewis, and Ali Davoudi",v:"IEEE Transactions on Neural Networks and Learning Systems",i:"distributedminmax.jpg",u:"https://ieeexplore.ieee.org/document/9933469"},
  {y:2024,t:"Inverse Reinforcement Learning for Trajectory Imitation Using Static Output Feedback Control",a:"Wenqian Xue, Bosen Lian, Jialu Fan, Tianyou Chai, and Frank L. Lewis",v:"IEEE Transactions on Cybernetics",i:"xue2023trajectoryimation.jpg",u:"https://ieeexplore.ieee.org/document/10045775"},
  {y:2024,t:"Inverse Q-Learning Using Input–Output Data",a:"Bosen Lian, Wenqian Xue, Frank L. Lewis, and Ali Davoudi",v:"IEEE Transactions on Cybernetics",i:"dia.png",u:"https://ieeexplore.ieee.org/abstract/document/10372113"},
  {y:2023,t:"Off-Policy Inverse Q-Learning for Discrete-Time Antagonistic Unknown Systems",a:"Bosen Lian, Wenqian Xue, Yijing Xie, Frank L. Lewis, and Ali Davoudi",v:"Automatica",i:"lian2023offinverseQ.jpg",u:"https://www.sciencedirect.com/science/article/pii/S0005109823003321"},
  {y:2023,t:"Inverse Reinforcement Learning for Adversarial Apprentice Games",a:"Bosen Lian, Wenqian Xue, Frank L. Lewis, and Tianyou Chai",v:"IEEE Transactions on Neural Networks and Learning Systems",i:"irlaag.jpg",u:"https://ieeexplore.ieee.org/document/9565156"},
  {y:2023,t:"Inverse Reinforcement Q-Learning Through Expert Imitation for Discrete-Time Systems",a:"Wenqian Xue, Bosen Lian, Jialu Fan, Patrik Kolaric, Tianyou Chai, and Frank L. Lewis",v:"IEEE Transactions on Neural Networks and Learning Systems",i:"xue2021inverseQ.jpg",u:"https://ieeexplore.ieee.org/abstract/document/9537731"},
  {y:2022,t:"Robust Inverse Q-Learning for Continuous-Time Linear Systems in Adversarial Environments",a:"Bosen Lian, Wenqian Xue, Frank L. Lewis, and Tianyou Chai",v:"IEEE Transactions on Cybernetics",i:"robust-inverseQ.jpg",u:"https://ieeexplore.ieee.org/abstract/document/9515769"},
  {y:2022,t:"Inverse Reinforcement Learning for Multi-Player Noncooperative Apprentice Games",a:"Bosen Lian, Wenqian Xue, Frank L. Lewis, and Tianyou Chai",v:"Automatica",i:"multi-player_noncooperative.jpg",u:"https://www.sciencedirect.com/science/article/pii/S0005109822003843"},
  {y:2022,t:"Inverse Reinforcement Learning in Tracking Control Based on Inverse Optimal Control",a:"Wenqian Xue, Patrik Kolaric, Jialu Fan, Bosen Lian, Tianyou Chai, and Frank L. Lewis",v:"IEEE Transactions on Cybernetics",i:"irlioc.jpg",u:"https://ieeexplore.ieee.org/abstract/document/9409781"},
  {y:2021,t:"Inverse Reinforcement Learning for Multi-Player Apprentice Games in Continuous-Time Nonlinear Systems",a:"Bosen Lian, Wenqian Xue, Frank L. Lewis, Tianyou Chai, and Ali Davoudi",v:"IEEE Conference on Decision and Control",i:"IRLcdc2021.png",u:"https://ieeexplore.ieee.org/abstract/document/9682909"},
  {y:2021,t:"Online Inverse Reinforcement Learning for Nonlinear Systems With Adversarial Attacks",a:"Bosen Lian, Wenqian Xue, Frank L. Lewis, and Tianyou Chai",v:"International Journal of Robust and Nonlinear Control",i:"onlineinverseattack.jpg",u:"https://onlinelibrary.wiley.com/doi/full/10.1002/rnc.5626"}
];

const list=document.querySelector('#publication-list');
function emphasize(name){return name.replaceAll('Wenqian Xue','<strong>Wenqian Xue</strong>')}
function render(filter='all'){
  const rows=publications.filter(p=>filter==='all'||String(p.y)===filter||(filter==='earlier'&&p.y<2024));
  list.innerHTML=rows.map(p=>`<article class="pub"><div class="pub-year">${p.y}</div><img class="pub-image" loading="lazy" src="assets/${p.i}" alt="Research figure for ${p.t}"><div><h3>${p.t}</h3><p class="pub-authors">${emphasize(p.a)}</p><p class="pub-venue">${p.v}</p></div><a class="paper-link" href="${p.u}" target="_blank" rel="noopener" aria-label="Open ${p.t}">↗</a></article>`).join('');
}
document.querySelectorAll('.filters button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)}));
const toggle=document.querySelector('.nav-toggle'),nav=document.querySelector('#nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
document.querySelector('#year').textContent=new Date().getFullYear();render();
